FROM alpine:latest

ENV DEBUG=false
ENV MC_VERSION="latest"
ENV MC_LOADER="vanilla"

RUN apk update && apk add --no-cache bash wget findutils gawk

RUN apk add --no-cache openjdk25

RUN mkdir -p /scripts/files
RUN mkdir -p /data/minecraft

COPY jvm_args.txt /scripts/files/jvm_args.txt
COPY init /scripts/files/init
COPY Install.sh /scripts/Install.sh
COPY Daemon.sh /scripts/Daemon.sh

WORKDIR /data/minecraft

EXPOSE 25565

ENTRYPOINT ["/bin/bash", "/scripts/Daemon.sh"]
