FROM alpine:latest

RUN apk update && apk add --no-cache bash wget

RUN apk add --no-cache openjdk21

RUN mkdir /scripts
RUN mkdir /minecraft

COPY Prep.sh /scripts/Prep.sh
COPY Daemon.sh /scripts/Daemon.sh

WORKDIR /minecraft

EXPOSE 25565

ENTRYPOINT ["/bin/bash", "/scripts/Daemon.sh"]
